### ISSUE TITLE
Cleaner odometry node

### ISSUE THREAD

**Issue by SyrianSpock** [cvra/goldorak#11]
- [Unused variable](https://github.com/cvra/goldorak/blob/master/goldorak_diffbase/src/odometry_node.cpp#L38) should be removed
- [Odometry update](https://github.com/cvra/goldorak/blob/master/goldorak_diffbase/src/odometry_node.cpp#L43) should be done out of the callback, we could trigger the odometry update via a binary semaphore or event to signal the new measurement reception.
- Take time to measure performances of the asynchronous odometry
- Establish and implement calibration process

**Comment by antoinealb** [comment]
Why should the odometry update be done out of the callback ? If we want to do it the best synchronization primitive would be a barrier to update only when both wheels have got a new measurements.

**Comment by SyrianSpock** [comment]
That's what I was thinking:
1. When we get an update for a wheel, we send an event or set a semaphore
2. When both wheels have signaled a measurement, we update the estimated pose and clear events / semaphores

**Comment by SyrianSpock** [comment]
I was wrong on this one, we need to update the odometry for each encoder received as the most recent encoder serves as reference while the older encoder is interpolated to current time.

This is done now on the master branch https://github.com/cvra/goldorak/commit/d3c6d322821a3402ae45f6ec556284e27558b843 and it fixes the problems observed by @Stapelzeiger a few days ago.

**Comment by antoinealb** [comment]
Good job :+1: The problems you are referring to is the offset when returning to zero angle ?

**Comment by SyrianSpock** [comment]
Yup.
We still need to do proper calibration, but I did some rough measurements and all seems good.
